---
# Configuration for your virtual machine
vm-config:
    - memory: "2048"
      cpus: "1"

# Specify the path for each folder you'd like to share with the virtual machine
folders:
    - map: /Users/me/path/to/code
      to: /home/vagrant/path/to/code